### PR TITLE
Python - Removed dependency on the tensorflow package

### PR DESCRIPTION
**Pull request by Ark-kun**
Fixes https://github.com/google/ml-metadata/issues/25

### CODE REVIEW

**Comment by hughmiao** [comment]
thanks for the change, @Ark-kun ! fork the tf error lgtm, however, it will break client side error handling, e.g., tfx [1]. If possible, please send a CL instead of a PR, so we can run all related tests. wdyt?

[1] https://github.com/tensorflow/tfx/blob/6e7d729e05acc957fa32338946aa26bc1c35945b/tfx/orchestration/metadata.py#L664

**Comment by mmuppidi** [comment]
@hughmiao any idea when this will go through ?

**Comment by hughmiao** [comment]
hi @mmuppidi, we have an internal cl under review which checks the dependencies to other projects; please stay tuned.

**Comment by gosandhya** [comment]
@hughmiao is there any update regarding this?

**Comment by StefanoFioravanzo** [comment]
@hughmiao We would love to see this PR merged, one of our critical projects relies on ml-metadata and it is a pain having to install TF - this dependency alone makes our docker images much bigger in size.

**Comment by hughmiao** [comment]
@StefanoFioravanzo thanks, we'd like this PR getting in, and drop py dependency to tf.

@Ark-kun friendly ping. Shall we prioritize the CL to move this forward?

**Comment by StefanoFioravanzo** [comment]
Hello @hughmiao @yiqin @Ark-kun friendly ping 😄  Is there any chance we could have this merged?

**Comment by hughmiao** [comment]
thanks all for the effort and interests. The change is addressed in the recent commit a94c9c4, which will be included in the next release.

**Pull request closed without merging**
