### PR TITLE
Added (conceptual) ml metadata er diagram

### PR DESCRIPTION
**Pull request by htahir1**
I noticed there was no documentation for entity relationships between the tables created by the ml-metadata store. This lead me to investigate and discover that the database itself has implicit relations and not explicit ones, at least with the SQLite and MySQL implementations (which in itself is a bit odd).

In any case, relations need to be documented to further understanding of this database. I thought I would draw the ER diagram and map the relations as I see them. I hope that is helpful for future developers, and if there is a mistake please do let me know and ill amend the source and regenerate the pgn accordingly.

### CODE REVIEW

**Comment by hughmiao** [comment]
@htahir1 thanks, Hamza. Note the MLMD physical schema is not documented by design, and it is hidden from the end users, as we may change it in any CLs to support new concepts in the data model, or optimize query performance. Any tools or code relying on the physical schema directly is fragile w.r.t. those schema changes.

Please refer to the [conceptual data model](https://github.com/google/ml-metadata/blob/master/g3doc/get_started.md#getting-started-with-ml-metadata) and use the high level APIs directly. Those are much more stable, and we make it backward compatible as much as possible.

**Comment by htahir1** [comment]
@hughmiao thank you for your reply. If that is the case, could you kindly let me know if the diagram represents the current status quo? Or have i made a mistake in there?

I am asking because in our company we are writing small scripts to do 'clean up' of our TFX pipelines. That means we need to read the ML Metadata database, see the relevant artifacts, delete them from Google Cloud Storage (or wherever really), and then delete the relevant entries in the database.

For this, we do need to know the internal details on the database.

Do you think this PR is still relevant in that context? Would people not like to know at least the current status quo of the ER diagrams to try to edit the ML metadata store?

**Comment by hughmiao** [comment]
@htahir1 , the schema is an implementation detail, and currently maintained [here](https://github.com/google/ml-metadata/blob/master/ml_metadata/util/metadata_source_query_config.cc). Depends on the backend (sqlite/mysql), you can generate the er from there. Note this is not a public API, we may change it on the head anytime.   

Back to your use case, `clean up` of TFX pipeline can be done by pipeline/environment isolation, i.e., for each pipeline, you can use a separate `db` to keep the metadata. e.g., sqlite is a file, mysql is a db. You can also setup some scratch db for dev environment. So you can drop the db instead of relying on the details of the physical schema. For production db with TFX, we currently don't provide delete APIs due to the small footprint of the metadata, and the provenance values of the lineage. 

Just curious about your setup of MLMD in Google cloud storage, what's your usage pattern here? I'm wondering whether the db size is a concern for you?

**Comment by htahir1** [comment]
@hughmiao thanks for the clarifications. So your recommendation is to isolate groups of experiments together and then just drop them when they arent relevant. a bit risky in my opinion but still we will consider it internally.

regarding size, no we dont have any problems on database size at the moment. its more about the artifact size on google cloud storage (we are using TFX and intermediate steps can create data of many many GB's)

**Comment by hughmiao** [comment]
@htahir1 , thanks for sharing the usage pattern. 

> no we dont have any problems on database size at the moment. its more about the artifact size on google cloud storage 

For this case, I felt you can still keep the metadata as it is even the artifact is deleted from the cloud storage. It shows information about what/when had run. 

Close this for now. Thanks for contributing and discussing your use case with us.

**Pull request closed without merging**
